global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using SurveyBasket.Domain.Entities;
global using SurveyBasket.Entities;
global using System.Reflection;
global using System.Security.Claims;
global using SurveyBasket.Application.Abstractions.Abstractions.Const;
